export const SHOW_FORMULARIO = 'SHOW_FORMULARIO'
export const GET_POSTS = 'GET_POSTS'
export const CURRENT_POST = 'CURRENT_POST'
export const CREATE_POST = 'CREATE_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const DELETE_POST = 'DELETE_POST'
export const GET_POST = 'GET_POST'
export const POST_NULL = 'POST_NULL'